### ISSUE TITLE
Channel Launch

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/sms77#1]
- [x] Code Review
- [x] Add to website
- [x] Create packagist package
- [x] Github actions
- [x] Style CI
- [x] Scrutinizer 
- [x] Add badges

**Comment by atymic** [comment]
Website PR pending tag of first release:
https://github.com/laravel-notification-channels/website/pull/25

**Comment by atymic** [comment]
@mxschll tag first release whenever you are ready :D

**Comment by mxschll** [comment]
@atymic Done, thanks (:

**Comment by atymic** [comment]
Website PR merged 🎉
We are live.
